Testing

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -12,6 +12,11 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
     inputs:
+      DEVICE:
+        description: 'Device the tests shall run on'
+        required: true
+        default:
+          'DESKTOP'
       RUN_NAME:
         description: 'The name of the run'
         required: true
@@ -29,98 +34,99 @@ permissions:
 #  group: "pages"
 #  cancel-in-progress: false
 
+
 jobs:
-  printInputs:
+  # Build job
+  build:
     runs-on: ubuntu-latest
     steps:
+
       - name: Save variable and print
         env:
           RUN_NAME: ${{ inputs.RUN_NAME }}"
+          DEVICE: ${{ inputs.DEVICE }}"
         run: |
           echo "PRINTING VARIABLE NAME: $RUN_NAME"
+          echo "PRINTING VARIABLE DEVICE: $DEVICE
+          "
       - name: Print input
         run: |
-          echo "Log level: ${{ inputs.RUN_NAME }}"
+          echo "ECHO: ${{ inputs.RUN_NAME }}"
+          echo "ECHO: ${{ inputs.DEVICE }}"
+          
 
-#jobs:
-#  # Build job
-#  build:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v3
-#      - name: Detect package manager
-#        id: detect-package-manager
-#        run: |
-#          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-#            echo "manager=yarn" >> $GITHUB_OUTPUT
-#            echo "command=install" >> $GITHUB_OUTPUT
-#            echo "runner=yarn" >> $GITHUB_OUTPUT
-#            exit 0
-#          elif [ -f "${{ github.workspace }}/package.json" ]; then
-#            echo "manager=npm" >> $GITHUB_OUTPUT
-#            echo "command=ci" >> $GITHUB_OUTPUT
-#            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-#            exit 0
-#          else
-#            echo "Unable to determine package manager"
-#            exit 1
-#          fi
-#      - name: Setup Node
-#        uses: actions/setup-node@v3
-#        with:
-#          node-version: "16"
-#          cache: ${{ steps.detect-package-manager.outputs.manager }}
-#      - name: Setup Pages
-#        uses: actions/configure-pages@v3
-#        with:
-#          # Automatically inject basePath in your Next.js configuration file and disable
-#          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
-#          #
-#          # You may remove this line if you want to manage the configuration yourself.
-#          static_site_generator: next
-#      - name: Restore cache
-#        uses: actions/cache@v3
-#        with:
-#          path: |
-#            .next/cache
-#          # Generate a new cache whenever packages or source files change.
-#          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-#          # If source files changed but packages didn't, rebuild from a prior cache.
-#          restore-keys: |
-#            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-#      - name: Install dependencies
-#        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-#      - name: Build with Next.js
-#        run: ${{ steps.detect-package-manager.outputs.runner }} next build
-#      - name: Static HTML export with Next.js
-#        run: ${{ steps.detect-package-manager.outputs.runner }} next export
-#      - name: Upload artifact
-#        uses: actions/upload-pages-artifact@v2
-#        with:
-#          path: ./out
-#      - name: Export regression run name to variable
-#        run: ${{ github.event.inputs.runName }} >> $RUN_NAME
-#      - name: Print contents of folder recursively
-#        run: ls -R
-#
-#  # Deployment job
-#  deploy:
-#    environment:
-#      name: github-pages
-#      url: ${{ steps.deployment.outputs.page_url }}
-#    runs-on: ubuntu-latest
-#    needs: build
-#    steps:
-#      - name: Deploy to GitHub Pages
-#        id: deployment
-#        uses: actions/deploy-pages@v2
-#
-#      # Run Cypress tests
-#      - name: Checkout
-#        uses: actions/checkout@v3
-#      - name: Printing directory
-#        run: pwd
-#      - name: Cypress run
-#        uses: cypress-io/github-action@v5
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v3
+        with:
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: next
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Static HTML export with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next export
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v2
+        with:
+          path: ./out
+      - name: Print contents of folder recursively
+        run: ls -R
+
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v2
+
+      # Run Cypress tests
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Printing directory
+        run: pwd
+      - name: Cypress run
+        uses: cypress-io/github-action@v5
 
